use_frameworks!

target 'VDLocalization_Example' do
  pod 'VDLocalization', :path => '../'

  target 'VDLocalization_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0'
    pod 'FBSnapshotTestCase' , '~> 2.1.4'
    pod 'Nimble-Snapshots' , '~> 6.3.0'
    pod 'Alamofire'
    pod 'SwiftyJSON'
  end
end
